import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { exigirPapel } from "@/lib/authz";

const esc=(v:unknown)=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
const date=(v:any)=>v?new Date(v).toLocaleString("pt-BR"):"—";
export async function GET(req:NextRequest){
 const { erro }=await exigirPapel();if(erro)return erro;
 const id=req.nextUrl.searchParams.get("id");if(!id)return new Response("id obrigatório",{status:400});
 const wo=(await prisma.$queryRaw<any[]>`SELECT wo.*,c.number AS contract_number,c.object AS contract_object,cl.name AS client_name FROM erp_work_order wo LEFT JOIN "Contract" c ON c.id=wo.contract_id LEFT JOIN "Client" cl ON cl.id=wo.client_id WHERE wo.id=${id} LIMIT 1`)[0];
 if(!wo)return new Response("OS não encontrada",{status:404});
 const [employees,equipment,checks,photos,signatures]=await Promise.all([
  prisma.$queryRaw<any[]>`SELECT e.name,e.role FROM erp_work_order_employee x JOIN "Employee" e ON e.id=x.employee_id WHERE x.work_order_id=${id} ORDER BY e.name`,
  prisma.$queryRaw<any[]>`SELECT e.descricao,e.tipo,e.codigo FROM erp_work_order_equipment x JOIN "Equipment" e ON e.id=x.equipment_id WHERE x.work_order_id=${id} ORDER BY e.descricao`,
  prisma.$queryRaw<any[]>`SELECT * FROM erp_work_order_checklist WHERE work_order_id=${id} ORDER BY category,sort_order`,
  prisma.$queryRaw<any[]>`SELECT * FROM erp_work_order_photo WHERE work_order_id=${id} ORDER BY photo_type,captured_at`,
  prisma.$queryRaw<any[]>`SELECT * FROM erp_work_order_signature WHERE work_order_id=${id} ORDER BY signed_at`,
 ]);
 const imgs=(type:string)=>photos.filter(x=>x.photo_type===type).map(x=>`<figure><img src="${esc(x.file_path)}"><figcaption>${esc(x.caption||type)} · ${date(x.captured_at)}</figcaption></figure>`).join("")||"<p>Sem registros.</p>";
 const html=`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>${esc(wo.number)} — Relatório</title><style>@page{size:A4;margin:15mm}body{font:12px Arial;color:#1f2937}h1,h2{color:#334532}header{border-bottom:3px solid #4a9410;margin-bottom:14px}.meta{display:grid;grid-template-columns:1fr 1fr;gap:5px;background:#f3f4f6;padding:10px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #d1d5db;padding:6px;text-align:left}th{background:#e8f5ee}figure{margin:0 0 10px;break-inside:avoid}img{width:100%;max-height:310px;object-fit:contain;border:1px solid #d1d5db}figcaption{font-size:10px;color:#6b7280}.assin{display:grid;grid-template-columns:1fr 1fr;gap:12px}.assin div{border:1px solid #d1d5db;padding:10px;min-height:80px}.assin img{max-height:55px}</style></head><body><header><h1>VERDELIMP — RELATÓRIO DE ORDEM DE SERVIÇO</h1><strong>${esc(wo.number)} — ${esc(wo.title)}</strong></header><section class="meta"><div><b>Cliente:</b> ${esc(wo.client_name||"—")}</div><div><b>Contrato:</b> ${esc(wo.contract_number||"Avulso")}</div><div><b>Serviço:</b> ${esc(wo.service_type)}</div><div><b>Status:</b> ${esc(wo.status)}</div><div><b>Local:</b> ${esc(wo.location)}, ${esc(wo.city)}/${esc(wo.state)}</div><div><b>Execução:</b> ${date(wo.actual_start)} a ${date(wo.actual_end)}</div><div><b>Supervisor:</b> ${esc(wo.supervisor||"—")}</div><div><b>Gerado em:</b> ${date(new Date())}</div></section><h2>Equipe e equipamentos</h2><div class="grid"><table><thead><tr><th>Funcionário</th><th>Função</th></tr></thead><tbody>${employees.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.role)}</td></tr>`).join("")}</tbody></table><table><thead><tr><th>Equipamento</th><th>Tipo</th></tr></thead><tbody>${equipment.map(x=>`<tr><td>${esc(x.codigo)} — ${esc(x.descricao)}</td><td>${esc(x.tipo)}</td></tr>`).join("")}</tbody></table></div><h2>Checklist</h2><table><thead><tr><th>Categoria</th><th>Item</th><th>Situação</th><th>Responsável</th></tr></thead><tbody>${checks.map(x=>`<tr><td>${esc(x.category)}</td><td>${esc(x.item)}</td><td>${x.completed?"CONCLUÍDO":"PENDENTE"}</td><td>${esc(x.completed_by||"—")}</td></tr>`).join("")}</tbody></table><h2>Registro fotográfico — Antes</h2><div class="grid">${imgs("BEFORE")}</div><h2>Registro fotográfico — Depois</h2><div class="grid">${imgs("AFTER")}</div><h2>Ocorrências e equipe</h2><div class="grid">${imgs("OCCURRENCE")}${imgs("TEAM")}</div><h2>Assinaturas e aceite eletrônico</h2><div class="assin">${signatures.map(x=>`<div><b>${esc(x.signer_type)} — ${esc(x.signer_name)}</b><br><img src="${esc(x.signature_path)}"><br><small>${esc(x.consent_text)}<br>${date(x.signed_at)}</small></div>`).join("")}</div><script>window.onload=()=>window.print()</script></body></html>`;
 return new Response(html,{headers:{"Content-Type":"text/html; charset=utf-8","Content-Disposition":`inline; filename="${wo.number}-relatorio.html"`}});
}
