"use client";
import { useEffect, useState } from "react";
import { estiloInput, estiloLabel } from "@/lib/estilos";
const current=()=>new Date().toISOString().slice(0,7);const money=(v:any)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export default function FolhaCompetencias(){
 const [comp,setComp]=useState(current());const [period,setPeriod]=useState<any>(null);const [periods,setPeriods]=useState<any[]>([]);const [preview,setPreview]=useState<any[]>([]);const [msg,setMsg]=useState("");const [edit,setEdit]=useState<any>(null);
 const loadList=()=>fetch("/api/folha/competencias").then(r=>r.json()).then(j=>setPeriods(j.periods||[]));
 const load=()=>fetch(`/api/folha/competencias?competence=${comp}`).then(r=>r.json()).then(j=>{setPeriod(j.period);setPreview(j.preview||[])});useEffect(()=>{loadList();load();},[]);useEffect(()=>{load();},[comp]);
 const generate=async()=>{const r=await fetch("/api/folha/competencias",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"generate",competence:comp,extras:{}})});const j=await r.json();setMsg(r.ok?"✅ Folha gerada e salva.":j.error||"Erro");if(r.ok){setPeriod(j.period);loadList();}};
 const update=async()=>{const r=await fetch("/api/folha/competencias",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"update",entryId:edit.id,benefits:Number(edit.benefits||0),advances:Number(edit.advances||0),thirteenthSalary:Number(edit.thirteenth_salary||0),vacationPay:Number(edit.vacation_pay||0),bonuses:Number(edit.bonuses||0),otherEarnings:Number(edit.other_earnings||0),otherDeductions:Number(edit.other_deductions||0),events:edit.events||[]})});const j=await r.json();setMsg(r.ok?"✅ Eventos atualizados.":j.error||"Erro");if(r.ok){setEdit(null);load();loadList();}};
 const close=async(action:string)=>{const r=await fetch("/api/folha/competencias",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,competence:comp,paymentDate:new Date().toISOString().slice(0,10)})});const j=await r.json();setMsg(r.ok?`✅ Competência ${action==="close"?"fechada":"reaberta"}.`:j.error||"Erro");if(r.ok){setPeriod(j.period);loadList();}};
 const pay=async(x:any)=>{await fetch("/api/folha/competencias",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"pay",entryId:x.id})});load();loadList();};
 const tot=(k:string)=>(period?.entries||[]).reduce((s:number,x:any)=>s+Number(x[k]||0),0);
 return <div><div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap",marginBottom:12}}><div><h1 style={{margin:0,color:"#334532",fontSize:22}}>📑 Folha por competência</h1><p style={{fontSize:12,color:"#6b7280",margin:"4px 0 0"}}>Histórico mensal, benefícios, adiantamentos, férias, 13º, pagamentos e comprovantes.</p></div><div><label style={estiloLabel}>Competência</label><input type="month" style={{...estiloInput,width:160}} value={comp} onChange={e=>setComp(e.target.value)}/></div></div>{msg&&<div style={{padding:9,background:"#fef9c3",color:"#92400e",borderRadius:8,marginBottom:10,fontSize:12}}>{msg}</div>}
 {!period&&<div style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:12,padding:16,marginBottom:12}}><h3 style={{fontSize:14,color:"#334532"}}>Competência ainda não gerada</h3><p style={{fontSize:11,color:"#6b7280"}}>{preview.length} funcionário(s) ativo(s) serão incluídos. O cálculo inicial usa as tabelas fiscais versionadas e permanece sujeito à validação contábil.</p><button onClick={generate} style={{background:"#4a9410",color:"#fff",border:0,borderRadius:8,padding:"9px 18px",fontWeight:700}}>Gerar e salvar folha</button></div>}
 {period&&<><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:9,marginBottom:12}}>{[["Bruto",tot("gross_amount")],["Líquido",tot("net_amount")],["Custo empresa",tot("company_cost")],["Não pagos",(period.entries||[]).filter((x:any)=>!x.paid_at).length]].map(([l,v],i)=><div key={l as string} style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:10,padding:12}}><div style={{fontSize:10,color:"#6b7280",fontWeight:700}}>{l}</div><div style={{fontSize:19,fontWeight:800,color:i===3&&v?"#dc2626":"#334532"}}>{i===3?v:money(v)}</div></div>)}</div><div style={{display:"flex",gap:8,marginBottom:10}}>{period.status==="CLOSED"?<button onClick={()=>close("reopen")} style={{border:0,borderRadius:8,padding:"7px 13px"}}>Reabrir competência</button>:<><button onClick={generate} style={{border:0,borderRadius:8,padding:"7px 13px"}}>Recalcular base</button><button onClick={()=>close("close")} style={{background:"#334532",color:"#fff",border:0,borderRadius:8,padding:"7px 13px",fontWeight:700}}>Fechar competência</button></>}</div><div style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:12,overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr style={{background:"#e8f5ee"}}>{["Funcionário","Salário base","Bruto","Benefícios","Adiantamentos","13º","Férias","Líquido","Custo empresa","Pagamento","Ações"].map(x=><th key={x} style={{padding:8,textAlign:"right"}}>{x}</th>)}</tr></thead><tbody>{period.entries.map((x:any)=><tr key={x.id} style={{borderTop:"1px solid #f3f4f6"}}><td style={{padding:8,textAlign:"left",fontWeight:700}}>{x.employee_name}<div style={{fontSize:9,color:"#6b7280"}}>{x.employee_role}</div></td><td style={{padding:8,textAlign:"right"}}>{money(x.base_salary)}</td><td style={{padding:8,textAlign:"right"}}>{money(x.gross_amount)}</td><td style={{padding:8,textAlign:"right"}}>{money(x.benefits)}</td><td style={{padding:8,textAlign:"right"}}>{money(x.advances)}</td><td style={{padding:8,textAlign:"right"}}>{money(x.thirteenth_salary)}</td><td style={{padding:8,textAlign:"right"}}>{money(x.vacation_pay)}</td><td style={{padding:8,textAlign:"right",fontWeight:800,color:"#15803d"}}>{money(x.net_amount)}</td><td style={{padding:8,textAlign:"right",color:"#dc2626"}}>{money(x.company_cost)}</td><td style={{padding:8,textAlign:"right",color:x.paid_at?"#15803d":"#991b1b"}}>{x.paid_at?new Date(x.paid_at).toLocaleDateString("pt-BR"):"Pendente"}</td><td style={{padding:8,textAlign:"right"}}><button onClick={()=>setEdit({...x})} disabled={period.status==="CLOSED"} style={{border:0,borderRadius:5,padding:"4px 7px"}}>Eventos</button>{!x.paid_at&&<button onClick={()=>pay(x)} style={{border:0,borderRadius:5,padding:"4px 7px",marginLeft:4,background:"#dcfce7",color:"#15803d"}}>Pagar</button>}</td></tr>)}</tbody></table></div></>}
 {edit&&<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,.4)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:50}}><div style={{background:"#fff",borderRadius:12,padding:18,width:"min(760px,94vw)"}}><h3 style={{marginTop:0,color:"#334532"}}>Eventos — {edit.employee_name}</h3><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:9}}>{[["benefits","Benefícios"],["advances","Adiantamentos"],["thirteenth_salary","13º salário"],["vacation_pay","Férias"],["bonuses","Bonificações"],["other_earnings","Outros proventos"],["other_deductions","Outros descontos"]].map(([k,l])=><div key={k}><label style={estiloLabel}>{l}</label><input type="number" step="0.01" style={estiloInput} value={edit[k]||0} onChange={e=>setEdit((p:any)=>({...p,[k]:Number(e.target.value)}))}/></div>)}</div><div style={{display:"flex",gap:8,marginTop:14}}><button onClick={update} style={{background:"#4a9410",color:"#fff",border:0,borderRadius:8,padding:"8px 18px",fontWeight:700}}>Salvar eventos</button><button onClick={()=>setEdit(null)} style={{border:0,borderRadius:8,padding:"8px 18px"}}>Cancelar</button></div></div></div>}
 <h2 style={{fontSize:13,color:"#334532",margin:"18px 0 8px"}}>Histórico</h2><div style={{display:"flex",gap:7,flexWrap:"wrap"}}>{periods.map(p=><button key={p.id} onClick={()=>setComp(p.competence)} style={{background:p.competence===comp?"#334532":"#fff",color:p.competence===comp?"#fff":"#374151",border:"1px solid #d1d5db",borderRadius:8,padding:"7px 11px",fontSize:11}}>{p.competence} · {money(p.net_total)} · {p.status}</button>)}</div></div>;
}
