"use client";
import { useEffect, useState, useCallback } from "react";
import { estiloInput, estiloLabel } from "@/lib/estilos";
const TIPOS:Record<string,string>={admissional:"Admissional",periodico:"Periódico",retorno_trabalho:"Retorno ao trabalho",mudanca_risco:"Mudança de risco/função",demissional:"Demissional"};
const UI:Record<string,[string,string,string]>={valido:["Válido","#dcfce7","#15803d"],a_vencer:["A vencer","#fef3c7","#92400e"],vencido:["Vencido","#fee2e2","#991b1b"]};const fdata=(d?:string|null)=>d?new Date(d).toLocaleDateString("pt-BR"):"—";
async function upload(file:File){const fd=new FormData();fd.append("file",file);const r=await fetch("/api/upload",{method:"POST",body:fd});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error||"Falha no upload");return j.url;}
export default function AsoPage(){
 const [dados,setDados]=useState<any>(null),[msg,setMsg]=useState(""),[aberto,setAberto]=useState("");const [form,setForm]=useState<any>({employeeId:"",examType:"periodico",examDate:"",expiresAt:"",result:"apto",doctor:"",crm:"",notes:"",filePath:""});
 const carregar=useCallback(async()=>setDados(await fetch("/api/aso").then(r=>r.json())),[]);useEffect(()=>{carregar();},[carregar]);
 const setExamDate=(v:string)=>{const sugestao=v?new Date(new Date(`${v}T12:00:00`).setFullYear(new Date(`${v}T12:00:00`).getFullYear()+1)).toISOString().slice(0,10):"";setForm((f:any)=>({...f,examDate:v,expiresAt:f.expiresAt||sugestao}));};
 const file=async(e:any)=>{const x=e.target.files?.[0];if(!x)return;try{const path=await upload(x);setForm((p:any)=>({...p,filePath:path}));setMsg("✅ Arquivo do ASO enviado.");}catch(e:any){setMsg(e.message)}};
 const salvar=async()=>{const r=await fetch("/api/aso",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await r.json();if(!r.ok){setMsg(j.error||"Erro");return;}setMsg("✅ ASO registrado e integrado ao monitor documental.");setForm({employeeId:"",examType:"periodico",examDate:"",expiresAt:"",result:"apto",doctor:"",crm:"",notes:"",filePath:""});carregar();};
 const remove=async(id:string)=>{if(!confirm("Excluir este ASO?"))return;await fetch(`/api/aso?id=${id}`,{method:"DELETE"});carregar();};
 if(!dados)return <p>Carregando...</p>;const card=(t:string,v:any,c:string)=><div style={{background:"#fff",borderRadius:12,padding:"14px 18px",flex:1,borderLeft:`4px solid ${c}`}}><p style={{margin:0,fontSize:11,color:"#6b7280",fontWeight:600}}>{t}</p><p style={{margin:"4px 0 0",fontSize:26,fontWeight:900,color:c}}>{v}</p></div>;
 return <div><h1 style={{fontSize:22,fontWeight:900,color:"#334532",marginBottom:4}}>🩺 ASO — Saúde Ocupacional</h1><p style={{color:"#6b7280",fontSize:13,marginBottom:16}}>Exames, arquivos, histórico e vencimentos integrados à documentação e mobilização.</p>{msg&&<div style={{padding:8,background:"#fef9c3",color:"#92400e",borderRadius:8,marginBottom:10,fontSize:12}}>{msg}</div>}<div style={{display:"flex",gap:12,marginBottom:18,flexWrap:"wrap"}}>{card("Funcionários ativos",dados.resumo.total,"#4a9410")}{card("Sem ASO",dados.resumo.semAso,"#374151")}{card("Vencidos",dados.resumo.vencidos,"#991b1b")}{card("A vencer (30d)",dados.resumo.aVencer,"#b45309")}</div>
 <div style={{background:"#fff",borderRadius:12,padding:16,marginBottom:18}}><h2 style={{fontSize:14,fontWeight:800,color:"#334532",margin:"0 0 12px"}}>➕ Registrar exame</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(155px,1fr))",gap:9}}><div><label style={estiloLabel}>Funcionário</label><select style={estiloInput} value={form.employeeId} onChange={e=>setForm((p:any)=>({...p,employeeId:e.target.value}))}><option value="">Selecione</option>{dados.linhas.map((l:any)=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div><div><label style={estiloLabel}>Tipo</label><select style={estiloInput} value={form.examType} onChange={e=>setForm((p:any)=>({...p,examType:e.target.value}))}>{Object.entries(TIPOS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div><label style={estiloLabel}>Data do exame</label><input type="date" style={estiloInput} value={form.examDate} onChange={e=>setExamDate(e.target.value)}/></div><div><label style={estiloLabel}>Válido até</label><input type="date" style={estiloInput} value={form.expiresAt} onChange={e=>setForm((p:any)=>({...p,expiresAt:e.target.value}))}/></div><div><label style={estiloLabel}>Resultado</label><select style={estiloInput} value={form.result} onChange={e=>setForm((p:any)=>({...p,result:e.target.value}))}><option value="apto">Apto</option><option value="apto_restricoes">Apto com restrições</option><option value="inapto">Inapto</option></select></div><div><label style={estiloLabel}>Médico</label><input style={estiloInput} value={form.doctor} onChange={e=>setForm((p:any)=>({...p,doctor:e.target.value}))}/></div><div><label style={estiloLabel}>CRM</label><input style={estiloInput} value={form.crm} onChange={e=>setForm((p:any)=>({...p,crm:e.target.value}))}/></div><div><label style={estiloLabel}>Arquivo ASO</label><input type="file" accept="application/pdf,image/*" onChange={file} style={{fontSize:11}}/>{form.filePath&&<a href={form.filePath} target="_blank" style={{fontSize:10}}>Arquivo enviado</a>}</div></div><button onClick={salvar} disabled={!form.employeeId||!form.examDate} style={{marginTop:11,background:"#4a9410",color:"#fff",border:0,padding:"9px 18px",borderRadius:8,fontWeight:700}}>Salvar</button></div>
 <div style={{background:"#fff",borderRadius:12,padding:16,overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr style={{borderBottom:"2px solid #e5e7eb",textAlign:"left"}}>{["Funcionário","Função","Último exame","Tipo","Válido até","Resultado","Arquivo","Status","Histórico"].map(x=><th key={x} style={{padding:8}}>{x}</th>)}</tr></thead><tbody>{dados.linhas.map((l:any)=>{const st=l.atual?.status;return <tr key={l.id} style={{borderBottom:"1px solid #f3f4f6"}}><td style={{padding:8,fontWeight:700}}>{l.name}</td><td style={{padding:8}}>{l.role}</td><td style={{padding:8}}>{fdata(l.atual?.examDate)}</td><td style={{padding:8}}>{l.atual?TIPOS[l.atual.examType]||l.atual.examType:"—"}</td><td style={{padding:8}}>{fdata(l.atual?.expiresAt)}</td><td style={{padding:8}}>{l.atual?.result||"—"}</td><td style={{padding:8}}>{l.atual?.filePath?<a href={l.atual.filePath} target="_blank">Abrir</a>:<span style={{color:"#991b1b"}}>Pendente</span>}</td><td style={{padding:8}}>{st&&UI[st]?<span style={{background:UI[st][1],color:UI[st][2],padding:"3px 8px",borderRadius:6,fontSize:11,fontWeight:700}}>{UI[st][0]}</span>:"Sem ASO"}</td><td style={{padding:8}}><button onClick={()=>setAberto(aberto===l.id?"":l.id)} style={{border:0,borderRadius:6,padding:"4px 8px"}}>{l.historico.length} anterior(es)</button></td></tr>})}</tbody></table>{dados.linhas.filter((l:any)=>l.id===aberto).map((l:any)=><div key={l.id} style={{marginTop:12,background:"#f9fafb",padding:10,borderRadius:8}}><strong style={{fontSize:12}}>Histórico de {l.name}</strong>{[l.atual,...l.historico].filter(Boolean).map((x:any)=><div key={x.id} style={{display:"flex",gap:10,padding:"6px 0",fontSize:11,borderBottom:"1px solid #e5e7eb"}}><span>{fdata(x.examDate)}</span><span>{TIPOS[x.examType]}</span><span>{fdata(x.expiresAt)}</span>{x.filePath&&<a href={x.filePath} target="_blank">Arquivo</a>}<button onClick={()=>remove(x.id)} style={{marginLeft:"auto",border:0,color:"#991b1b"}}>Excluir</button></div>)}</div>)}</div></div>;
}
