import { randomUUID } from "crypto";
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { erroInterno, exigirPapel } from "@/lib/authz";

export const dynamic="force-dynamic";
const Title=z.object({action:z.literal("save").default("save"),id:z.string().optional(),clientId:z.string().optional().nullable(),contractId:z.string().optional().nullable(),measurementId:z.string().optional().nullable(),nfseId:z.string().optional().nullable(),description:z.string().min(2).max(300),documentNumber:z.string().max(100).optional().nullable(),installmentNumber:z.coerce.number().int().min(1).default(1),installmentTotal:z.coerce.number().int().min(1).default(1),issueDate:z.string(),dueDate:z.string(),grossAmount:z.coerce.number().positive(),retentionAmount:z.coerce.number().min(0).default(0),costCenter:z.string().max(120).optional().nullable(),notes:z.string().max(1000).optional().nullable()});
const Payment=z.object({action:z.literal("payment"),receivableId:z.string(),amount:z.coerce.number().positive(),paidAt:z.string().optional(),paymentMethod:z.string().max(80).optional().nullable(),bankAccount:z.string().max(120).optional().nullable(),receiptPath:z.string().max(1000).optional().nullable(),notes:z.string().max(1000).optional().nullable()});
const FromMeasurement=z.object({action:z.literal("from_measurement"),measurementId:z.string(),dueDate:z.string(),retentionAmount:z.coerce.number().min(0).default(0)});
const dt=(v:string)=>new Date(`${v}T12:00:00`);
async function recalc(id:string){const rows=await prisma.$queryRaw<any[]>`SELECT r.net_amount,COALESCE(SUM(p.amount),0) AS paid FROM erp_receivable r LEFT JOIN erp_receivable_payment p ON p.receivable_id=r.id WHERE r.id=${id} GROUP BY r.id`;if(!rows[0])return;const paid=Number(rows[0].paid),net=Number(rows[0].net_amount);const status=paid<=0?"OPEN":paid<net?"PARTIAL":"RECEIVED";await prisma.$executeRaw`UPDATE erp_receivable SET status=${status},updated_at=NOW() WHERE id=${id}`;}
export async function GET(req:NextRequest){const{erro}=await exigirPapel("ADMIN","FINANCEIRO","CONTRATOS");if(erro)return erro;try{const status=req.nextUrl.searchParams.get("status");const rows=status?await prisma.$queryRaw<any[]>`SELECT r.*,cl.name AS client_name,c.number AS contract_number,COALESCE(SUM(p.amount),0) AS paid_amount FROM erp_receivable r LEFT JOIN "Client" cl ON cl.id=r.client_id LEFT JOIN "Contract" c ON c.id=r.contract_id LEFT JOIN erp_receivable_payment p ON p.receivable_id=r.id WHERE r.status=${status} GROUP BY r.id,cl.name,c.number ORDER BY r.due_date`:await prisma.$queryRaw<any[]>`SELECT r.*,cl.name AS client_name,c.number AS contract_number,COALESCE(SUM(p.amount),0) AS paid_amount FROM erp_receivable r LEFT JOIN "Client" cl ON cl.id=r.client_id LEFT JOIN "Contract" c ON c.id=r.contract_id LEFT JOIN erp_receivable_payment p ON p.receivable_id=r.id GROUP BY r.id,cl.name,c.number ORDER BY r.due_date DESC LIMIT 1000`;return NextResponse.json({data:rows});}catch(e){return erroInterno(e,"api/financeiro/contas-receber GET")}}
export async function POST(req:NextRequest){const{user,erro}=await exigirPapel("ADMIN","FINANCEIRO");if(erro)return erro;try{const raw=await req.json();if(raw.action==="payment"){const p=Payment.safeParse(raw);if(!p.success)return NextResponse.json({error:"Recebimento inválido",details:p.error.flatten()},{status:400});const b=p.data;const row=(await prisma.$queryRaw<any[]>`SELECT r.net_amount,COALESCE(SUM(p.amount),0) AS paid FROM erp_receivable r LEFT JOIN erp_receivable_payment p ON p.receivable_id=r.id WHERE r.id=${b.receivableId} GROUP BY r.id`)[0];if(!row)return NextResponse.json({error:"Título não encontrado"},{status:404});if(Number(row.paid)+b.amount>Number(row.net_amount)+0.01)return NextResponse.json({error:"Recebimento supera o saldo do título"},{status:409});await prisma.$executeRaw`INSERT INTO erp_receivable_payment(id,receivable_id,amount,paid_at,payment_method,bank_account,receipt_path,notes,registered_by)VALUES(${randomUUID()},${b.receivableId},${b.amount},${b.paidAt?new Date(b.paidAt):new Date()},${b.paymentMethod||null},${b.bankAccount||null},${b.receiptPath||null},${b.notes||null},${user?.email||user?.name||user?.id})`;await recalc(b.receivableId);return NextResponse.json({success:true});}
if(raw.action==="from_measurement"){const p=FromMeasurement.safeParse(raw);if(!p.success)return NextResponse.json({error:"Medição inválida"},{status:400});const m=await prisma.measurement.findUnique({where:{id:p.data.measurementId},include:{contract:{include:{client:true}}}});if(!m)return NextResponse.json({error:"Medição não encontrada"},{status:404});const existing=await prisma.$queryRaw<any[]>`SELECT id FROM erp_receivable WHERE measurement_id=${m.id} LIMIT 1`;if(existing[0])return NextResponse.json({error:"A medição já possui título a receber",id:existing[0].id},{status:409});const id=randomUUID(),gross=Number(m.value),net=gross-p.data.retentionAmount;await prisma.$executeRaw`INSERT INTO erp_receivable(id,client_id,contract_id,measurement_id,description,document_number,issue_date,due_date,gross_amount,retention_amount,net_amount,status,cost_center)VALUES(${id},${m.contract.clientId||null},${m.contractId},${m.id},${`Medição ${m.period} — ${m.contract.number}`},${m.period},${new Date()},${dt(p.data.dueDate)},${gross},${p.data.retentionAmount},${net},'OPEN',${m.contract.number})`;return NextResponse.json({success:true,id},{status:201});}
const p=Title.safeParse({...raw,action:"save"});if(!p.success)return NextResponse.json({error:"Título inválido",details:p.error.flatten()},{status:400});const b=p.data,id=b.id||randomUUID(),net=b.grossAmount-b.retentionAmount;if(net<0)return NextResponse.json({error:"Retenções não podem superar o valor bruto"},{status:400});await prisma.$executeRaw`INSERT INTO erp_receivable(id,client_id,contract_id,measurement_id,nfse_id,description,document_number,installment_number,installment_total,issue_date,due_date,gross_amount,retention_amount,net_amount,status,cost_center,notes,updated_at)VALUES(${id},${b.clientId||null},${b.contractId||null},${b.measurementId||null},${b.nfseId||null},${b.description},${b.documentNumber||null},${b.installmentNumber},${b.installmentTotal},${dt(b.issueDate)},${dt(b.dueDate)},${b.grossAmount},${b.retentionAmount},${net},'OPEN',${b.costCenter||null},${b.notes||null},NOW())ON CONFLICT(id)DO UPDATE SET client_id=EXCLUDED.client_id,contract_id=EXCLUDED.contract_id,measurement_id=EXCLUDED.measurement_id,nfse_id=EXCLUDED.nfse_id,description=EXCLUDED.description,document_number=EXCLUDED.document_number,installment_number=EXCLUDED.installment_number,installment_total=EXCLUDED.installment_total,issue_date=EXCLUDED.issue_date,due_date=EXCLUDED.due_date,gross_amount=EXCLUDED.gross_amount,retention_amount=EXCLUDED.retention_amount,net_amount=EXCLUDED.net_amount,cost_center=EXCLUDED.cost_center,notes=EXCLUDED.notes,updated_at=NOW()`;await recalc(id);return NextResponse.json({success:true,id},{status:b.id?200:201});}catch(e){return erroInterno(e,"api/financeiro/contas-receber POST")}}
