"use client";
import { useEffect, useState } from "react";
import { estiloInput, estiloLabel } from "@/lib/estilos";

const empty: any = { name:"", role:"", cpf:"", admissionDate:"", salary:"", dependentes:0, insalubridadeGrau:0, periculosidade:false, contractType:"CLT", weeklyHours:44, state:"MG" };
const d = (v: any) => v ? new Date(v).toISOString().slice(0,10) : "";

export default function RhAdmissaoPage(){
  const [list,setList]=useState<any[]>([]); const [form,setForm]=useState<any>(empty); const [msg,setMsg]=useState(""); const [open,setOpen]=useState(true);
  const load=()=>fetch("/api/rh/admissao-completa").then(r=>r.json()).then(j=>setList(j.data||[]));
  useEffect(()=>{load();},[]);
  const set=(k:string,v:any)=>setForm((p:any)=>({...p,[k]:v}));
  const edit=(x:any)=>{ const p=x.profile||{}; setForm({employeeId:x.id,name:x.name,role:x.role,cpf:x.cpf||"",admissionDate:d(x.admissionDate),salary:Number(x.salary),dependentes:x.dependentes||0,insalubridadeGrau:x.insalubridadeGrau||0,periculosidade:!!x.periculosidade,bank:x.bank||"",bankAgency:x.bankAgency||"",bankAccount:x.bankAccount||"",dateOfBirth:d(p.date_of_birth),rg:p.rg||"",rgIssuer:p.rg_issuer||"",ctps:p.ctps||"",pisPasep:p.pis_pasep||"",cnh:p.cnh||"",cnhCategory:p.cnh_category||"",cnhExpiresAt:d(p.cnh_expires_at),maritalStatus:p.marital_status||"",educationLevel:p.education_level||"",phone:p.phone||"",email:p.email||"",emergencyContactName:p.emergency_contact_name||"",emergencyContactPhone:p.emergency_contact_phone||"",street:p.street||"",number:p.number||"",complement:p.complement||"",neighborhood:p.neighborhood||"",city:p.city||"",state:p.state||"MG",postalCode:p.postal_code||"",contractType:p.contract_type||"CLT",weeklyHours:Number(p.weekly_hours||44),workSchedule:p.work_schedule||"",unionName:p.union_name||"",collectiveAgreement:p.collective_agreement||"",costCenter:p.cost_center||"",terminationDate:d(p.termination_date),terminationReason:p.termination_reason||"",terminationNotes:p.termination_notes||""}); setOpen(true); window.scrollTo({top:0,behavior:"smooth"}); };
  const save=async()=>{setMsg(""); const r=await fetch("/api/rh/admissao-completa",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,salary:Number(form.salary),dependentes:Number(form.dependentes),insalubridadeGrau:Number(form.insalubridadeGrau),weeklyHours:Number(form.weeklyHours)})}); const j=await r.json(); if(!r.ok){setMsg(j.error||"Erro");return;} setMsg("✅ Cadastro salvo e integrado ao RH."); setForm(empty); load();};
  const fields=(items:any[])=> <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:9}}>{items.map(([k,l,t="text",opts]:any)=><div key={k}><label style={estiloLabel}>{l}</label>{opts?<select style={estiloInput} value={form[k]??""} onChange={e=>set(k,e.target.value)}>{opts.map((o:any)=><option key={o} value={o}>{o}</option>)}</select>:<input style={estiloInput} type={t} value={form[k]??""} onChange={e=>set(k,t==="number"?Number(e.target.value):e.target.value)}/>}</div>)}</div>;
  return <div>
    <div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap",marginBottom:12}}><div><h1 style={{margin:0,color:"#334532",fontSize:22}}>👷 Admissão e ciclo do colaborador</h1><p style={{fontSize:12,color:"#6b7280",margin:"4px 0 0"}}>Cadastro completo, dados contratuais, endereço, emergência e desligamento.</p></div><div style={{display:"flex",gap:7}}><a href="/dashboard/checklist-docs" style={{padding:"8px 12px",background:"#e8f5ee",color:"#334532",borderRadius:8,textDecoration:"none",fontSize:12,fontWeight:700}}>Gerar documentos</a><button onClick={()=>{setForm(empty);setOpen(true)}} style={{padding:"8px 12px",background:"#334532",color:"#fff",border:0,borderRadius:8,fontWeight:700}}>+ Novo</button></div></div>
    {open&&<div style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:12,padding:16,marginBottom:14}}>
      <h3 style={{fontSize:13,color:"#334532"}}>Identificação e vínculo</h3>{fields([["name","Nome completo"],["cpf","CPF"],["dateOfBirth","Nascimento","date"],["rg","RG"],["rgIssuer","Órgão emissor"],["ctps","CTPS"],["pisPasep","PIS/PASEP"],["role","Função"],["admissionDate","Admissão","date"],["salary","Salário","number"],["contractType","Contrato","text",["CLT","Experiência","Prazo determinado","Aprendiz","Estágio","Outro"]],["weeklyHours","Horas semanais","number"],["workSchedule","Jornada/horário"],["costCenter","Centro de custos"],["unionName","Sindicato"],["collectiveAgreement","Convenção coletiva"]])}
      <h3 style={{fontSize:13,color:"#334532",marginTop:16}}>SST, bancário e documentos</h3>{fields([["insalubridadeGrau","Insalubridade %","number",[0,10,20,40]],["dependentes","Dependentes","number"],["cnh","CNH"],["cnhCategory","Categoria CNH"],["cnhExpiresAt","Validade CNH","date"],["bank","Banco"],["bankAgency","Agência"],["bankAccount","Conta"]])}<label style={{fontSize:11,display:"block",marginTop:8}}><input type="checkbox" checked={!!form.periculosidade} onChange={e=>set("periculosidade",e.target.checked)}/> Periculosidade</label>
      <h3 style={{fontSize:13,color:"#334532",marginTop:16}}>Contato e endereço</h3>{fields([["phone","Telefone"],["email","E-mail","email"],["emergencyContactName","Contato de emergência"],["emergencyContactPhone","Telefone de emergência"],["street","Logradouro"],["number","Número"],["complement","Complemento"],["neighborhood","Bairro"],["city","Município"],["state","UF"],["postalCode","CEP"],["maritalStatus","Estado civil"],["educationLevel","Escolaridade"]])}
      <h3 style={{fontSize:13,color:"#991b1b",marginTop:16}}>Desligamento — preencher somente quando aplicável</h3>{fields([["terminationDate","Data do desligamento","date"],["terminationReason","Motivo"],["terminationNotes","Observações"]])}
      {msg&&<div style={{marginTop:10,padding:8,borderRadius:7,background:msg.startsWith("✅")?"#dcfce7":"#fee2e2",color:msg.startsWith("✅")?"#15803d":"#991b1b",fontSize:12}}>{msg}</div>}
      <div style={{display:"flex",gap:8,marginTop:14}}><button onClick={save} disabled={!form.name||!form.role||!form.admissionDate||!form.salary} style={{background:"#4a9410",color:"#fff",border:0,borderRadius:8,padding:"9px 22px",fontWeight:700}}>💾 Salvar</button><button onClick={()=>setOpen(false)} style={{border:0,borderRadius:8,padding:"9px 18px"}}>Fechar</button></div>
    </div>}
    <div style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:12,overflow:"hidden"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr style={{background:"#e8f5ee",textAlign:"left"}}>{["Funcionário","Função","Admissão","Contrato","Centro de custos","Situação","Ações"].map(x=><th key={x} style={{padding:9}}>{x}</th>)}</tr></thead><tbody>{list.map(x=><tr key={x.id} style={{borderTop:"1px solid #f3f4f6"}}><td style={{padding:9,fontWeight:700}}>{x.name}<div style={{fontSize:10,color:"#6b7280"}}>{x.cpf||"CPF não informado"}</div></td><td style={{padding:9}}>{x.role}</td><td style={{padding:9}}>{new Date(x.admissionDate).toLocaleDateString("pt-BR")}</td><td style={{padding:9}}>{x.profile?.contract_type||"CLT"}</td><td style={{padding:9}}>{x.profile?.cost_center||"—"}</td><td style={{padding:9,color:x.active?"#15803d":"#991b1b",fontWeight:700}}>{x.active?"Ativo":"Desligado"}</td><td style={{padding:9}}><button onClick={()=>edit(x)} style={{border:0,background:"#dbeafe",color:"#1d4ed8",borderRadius:6,padding:"5px 9px"}}>Editar</button></td></tr>)}</tbody></table></div>
  </div>;
}
