"use client";
import { useEffect, useState } from "react";
import { estiloInput, estiloLabel } from "@/lib/estilos";
const money=(v:any)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
async function upload(file:File){const fd=new FormData();fd.append("file",file);const r=await fetch("/api/upload",{method:"POST",body:fd});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error||"Falha no upload");return j;}
export default function FinanceiroAnexos(){
 const [expenses,setExpenses]=useState<any[]>([]),[attachments,setAttachments]=useState<any[]>([]),[expenseId,setExpenseId]=useState(""),[kind,setKind]=useState("BOLETO"),[msg,setMsg]=useState("");
 const load=()=>{fetch("/api/financeiro").then(r=>r.json()).then(j=>setExpenses(j.data||[]));fetch("/api/financeiro/recorrencias").then(r=>r.json()).then(j=>setAttachments(j.attachments||[]));};useEffect(()=>{load();},[]);
 const file=async(e:any)=>{const x=e.target.files?.[0];if(!x||!expenseId)return;try{const u=await upload(x);const r=await fetch("/api/financeiro/recorrencias",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"attach",expenseId,kind,filePath:u.url,mimeType:u.mimeType,originalName:x.name})});const j=await r.json();setMsg(r.ok?"✅ Documento vinculado ao lançamento.":j.error||"Erro");if(r.ok)load();}catch(e:any){setMsg(e.message)}};
 return <div><h1 style={{margin:"0 0 4px",fontSize:22,color:"#334532"}}>📎 Boletos e comprovantes</h1><p style={{fontSize:12,color:"#6b7280",margin:"0 0 13px"}}>Vincule a evidência financeira diretamente à conta a pagar ou receber.</p>{msg&&<div style={{padding:9,background:"#fef9c3",color:"#92400e",borderRadius:8,marginBottom:10,fontSize:12}}>{msg}</div>}<div style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:12,padding:16,marginBottom:12}}><div style={{display:"grid",gridTemplateColumns:"3fr 1fr 1fr",gap:9,alignItems:"end"}}><div><label style={estiloLabel}>Lançamento</label><select style={estiloInput} value={expenseId} onChange={e=>setExpenseId(e.target.value)}><option value="">Selecione</option>{expenses.map(x=><option key={x.id} value={x.id}>{x.description} — {money(x.amount)} — {new Date(x.dueDate).toLocaleDateString("pt-BR")}</option>)}</select></div><div><label style={estiloLabel}>Tipo</label><select style={estiloInput} value={kind} onChange={e=>setKind(e.target.value)}><option>BOLETO</option><option>COMPROVANTE</option><option>NOTA_FISCAL</option><option>OUTRO</option></select></div><label style={{background:expenseId?"#334532":"#9ca3af",color:"#fff",padding:"8px 12px",borderRadius:8,fontSize:12,fontWeight:700,textAlign:"center",cursor:expenseId?"pointer":"default"}}>Enviar arquivo<input type="file" accept="application/pdf,image/*" hidden disabled={!expenseId} onChange={file}/></label></div></div><div style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:12,overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr style={{background:"#e8f5ee"}}>{["Tipo","Arquivo","Lançamento","Enviado por","Data"].map(x=><th key={x} style={{padding:8,textAlign:"left"}}>{x}</th>)}</tr></thead><tbody>{attachments.map(x=>{const expense=expenses.find(e=>e.id===x.expense_id);return <tr key={x.id} style={{borderTop:"1px solid #f3f4f6"}}><td style={{padding:8,fontWeight:700}}>{x.kind}</td><td style={{padding:8}}><a href={x.file_path} target="_blank">{x.original_name||"Abrir documento"}</a></td><td style={{padding:8}}>{expense?.description||x.expense_id}</td><td style={{padding:8}}>{x.uploaded_by||"—"}</td><td style={{padding:8}}>{new Date(x.created_at).toLocaleString("pt-BR")}</td></tr>})}</tbody></table></div></div>;
}
