"use client";
import { useEffect, useRef, useState } from "react";
import { estiloInput, estiloLabel } from "@/lib/estilos";
const money=(v:any)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const iso=()=>new Date().toISOString().slice(0,10);
const empty:any={description:"",amount:"",recurrence:"MONTHLY",dueDay:new Date().getDate(),startDate:iso(),nextDueDate:iso(),active:true};
const norm=(s:string)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]/g,"");
const aliases:any={description:["descricao","historico","despesa","nome"],amount:["valor","valorbruto","total"],dueDate:["vencimento","datavencimento","data"],paidAt:["pagamento","datapagamento"],status:["status","situacao"],categoryName:["categoria","grupo"],supplierName:["fornecedor","favorecido"],supplierCnpj:["cnpj","cnpjfornecedor"],competence:["competencia","mes"],costCenter:["centrodecusto","centrocustos"],contractNumber:["contrato","numerocontrato"],notes:["observacao","observacoes"]};
function parseCSV(text:string){const first=text.split(/\r?\n/)[0]||"";const sep=first.includes(";")?";":first.includes("\t")?"\t":",";const rows=text.split(/\r?\n/).filter(Boolean).map(line=>{const out=[];let cur="",quote=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quote&&line[i+1]==='"'){cur+='"';i++;}else quote=!quote;}else if(c===sep&&!quote){out.push(cur.trim());cur="";}else cur+=c;}out.push(cur.trim());return out;});const header=rows.shift()!.map(norm);const idx:any={};for(const [key,list] of Object.entries(aliases))idx[key]=header.findIndex(h=>(list as string[]).includes(h));const val=(r:string[],k:string)=>idx[k]>=0?r[idx[k]]:"";return rows.map((r,i)=>({description:val(r,"description"),amount:Number(val(r,"amount").replace(/\./g,"").replace(",",".")),dueDate:val(r,"dueDate").split("/").reverse().join("-"),paidAt:val(r,"paidAt")?val(r,"paidAt").split("/").reverse().join("-"):null,status:(val(r,"status")||"em_aberto").toLowerCase().replace(/ /g,"_"),categoryName:val(r,"categoryName")||null,supplierName:val(r,"supplierName")||null,supplierCnpj:val(r,"supplierCnpj")||null,competence:val(r,"competence")||null,costCenter:val(r,"costCenter")||null,contractNumber:val(r,"contractNumber")||null,notes:val(r,"notes")||null,sourceLine:i+2})).filter(x=>x.description&&x.amount&&x.dueDate);}
export default function FinanceiroAvancado(){
 const [tab,setTab]=useState("rec");const [rules,setRules]=useState<any[]>([]);const [f,setF]=useState<any>(empty);const [msg,setMsg]=useState("");const [preview,setPreview]=useState<any[]>([]);const [ai,setAi]=useState<any>(null);const [docText,setDocText]=useState("");const fileRef=useRef<HTMLInputElement>(null);
 const load=()=>fetch("/api/financeiro/recorrencias").then(r=>r.json()).then(j=>setRules(j.rules||[]));useEffect(()=>{load();},[]);const set=(k:string,v:any)=>setF((p:any)=>({...p,[k]:v}));
 const save=async()=>{const r=await fetch("/api/financeiro/recorrencias",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...f,action:"save",amount:Number(f.amount),dueDay:Number(f.dueDay)})});const j=await r.json();setMsg(r.ok?"✅ Conta recorrente salva.":j.error||"Erro");if(r.ok){setF(empty);load();}};
 const generate=async()=>{const until=new Date();until.setMonth(until.getMonth()+3);const r=await fetch("/api/financeiro/recorrencias",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"generate",until:until.toISOString().slice(0,10)})});const j=await r.json();setMsg(r.ok?`✅ ${j.generated} lançamento(s) gerado(s).`:j.error||"Erro");};
 const file=async(e:any)=>{const x=e.target.files?.[0];if(!x)return;const text=await x.text();const rows=parseCSV(text);setPreview(rows);setMsg(rows.length?`Prévia pronta: ${rows.length} linha(s).`:"Nenhuma linha válida. Use CSV com cabeçalhos descrição, valor e vencimento.");};
 const importRows=async()=>{const r=await fetch("/api/financeiro/importar-despesas",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rows:preview,fileName:fileRef.current?.files?.[0]?.name||"planilha.csv"})});const j=await r.json();setMsg(`Importados: ${j.imported||0} · duplicados: ${j.duplicates||0} · erros: ${j.errors?.length||0}`);if(r.ok)setPreview([]);};
 const extract=async()=>{setAi(null);const r=await fetch("/api/ia/extrair-documento-financeiro",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:docText,sourceName:"texto colado"})});const j=await r.json();if(!r.ok){setMsg(j.error||"Erro");return;}setAi(j);};
 const edit=(x:any)=>setF({id:x.id,description:x.description,amount:Number(x.amount),recurrence:x.recurrence,dueDay:x.due_day,startDate:new Date(x.start_date).toISOString().slice(0,10),endDate:x.end_date?new Date(x.end_date).toISOString().slice(0,10):"",nextDueDate:new Date(x.next_due_date).toISOString().slice(0,10),costCenter:x.cost_center||"",competencePrefix:x.competence_prefix||"",defaultNotes:x.default_notes||"",active:x.active});
 return <div><h1 style={{margin:"0 0 4px",color:"#334532",fontSize:22}}>💰 Financeiro avançado</h1><p style={{fontSize:12,color:"#6b7280",margin:"0 0 12px"}}>Contas recorrentes, importação de planilhas, anexos e leitura assistida por IA.</p><div style={{display:"flex",gap:7,marginBottom:12}}>{[["rec","Recorrências"],["import","Importar planilha"],["ia","Ler boleto/NF"]].map(([id,l])=><button key={id} onClick={()=>setTab(id)} style={{background:tab===id?"#334532":"#fff",color:tab===id?"#fff":"#374151",border:"1px solid #d1d5db",borderRadius:8,padding:"7px 13px"}}>{l}</button>)}</div>{msg&&<div style={{background:"#fef9c3",color:"#92400e",padding:9,borderRadius:8,marginBottom:10,fontSize:12}}>{msg}</div>}
 {tab==="rec"&&<><div style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:12,padding:15,marginBottom:12}}><div style={{display:"grid",gridTemplateColumns:"2fr 1fr 1fr 100px",gap:9}}><div><label style={estiloLabel}>Descrição</label><input style={estiloInput} value={f.description} onChange={e=>set("description",e.target.value)}/></div><div><label style={estiloLabel}>Valor</label><input type="number" style={estiloInput} value={f.amount} onChange={e=>set("amount",e.target.value)}/></div><div><label style={estiloLabel}>Recorrência</label><select style={estiloInput} value={f.recurrence} onChange={e=>set("recurrence",e.target.value)}><option value="WEEKLY">Semanal</option><option value="MONTHLY">Mensal</option><option value="QUARTERLY">Trimestral</option><option value="YEARLY">Anual</option></select></div><div><label style={estiloLabel}>Dia</label><input type="number" min="1" max="31" style={estiloInput} value={f.dueDay} onChange={e=>set("dueDay",e.target.value)}/></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:9,marginTop:9}}><div><label style={estiloLabel}>Início</label><input type="date" style={estiloInput} value={f.startDate} onChange={e=>set("startDate",e.target.value)}/></div><div><label style={estiloLabel}>Próximo vencimento</label><input type="date" style={estiloInput} value={f.nextDueDate} onChange={e=>set("nextDueDate",e.target.value)}/></div><div><label style={estiloLabel}>Término</label><input type="date" style={estiloInput} value={f.endDate||""} onChange={e=>set("endDate",e.target.value)}/></div><div><label style={estiloLabel}>Centro de custos</label><input style={estiloInput} value={f.costCenter||""} onChange={e=>set("costCenter",e.target.value)}/></div></div><div style={{display:"flex",gap:8,marginTop:10}}><button onClick={save} disabled={!f.description||!f.amount} style={{background:"#4a9410",color:"#fff",border:0,borderRadius:8,padding:"8px 18px",fontWeight:700}}>Salvar regra</button><button onClick={generate} style={{background:"#7c3aed",color:"#fff",border:0,borderRadius:8,padding:"8px 18px",fontWeight:700}}>Gerar próximos 3 meses</button></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:9}}>{rules.map(x=><div key={x.id} style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:10,padding:12}}><strong>{x.description}</strong><div style={{fontSize:18,fontWeight:800,color:"#dc2626",marginTop:4}}>{money(x.amount)}</div><div style={{fontSize:10,color:"#6b7280"}}>{x.recurrence} · próximo {new Date(x.next_due_date).toLocaleDateString("pt-BR")} · {x.cost_center||"sem centro de custos"}</div><button onClick={()=>edit(x)} style={{marginTop:7,border:0,borderRadius:6,padding:"4px 8px"}}>Editar</button></div>)}</div></>}
 {tab==="import"&&<div style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:12,padding:16}}><h3 style={{fontSize:14,color:"#334532"}}>Importar despesas</h3><p style={{fontSize:11,color:"#6b7280"}}>Salve a planilha como CSV. Cabeçalhos reconhecidos: descrição, valor, vencimento, pagamento, status, categoria, fornecedor, CNPJ, competência, centro de custo, contrato e observações. Duplicidades são bloqueadas.</p><input ref={fileRef} type="file" accept=".csv,text/csv" onChange={file}/>{preview.length>0&&<><div style={{overflowX:"auto",marginTop:12}}><table style={{width:"100%",fontSize:11,borderCollapse:"collapse"}}><thead><tr>{["Linha","Descrição","Valor","Vencimento","Categoria","Fornecedor"].map(x=><th key={x} style={{padding:6,textAlign:"left",background:"#e8f5ee"}}>{x}</th>)}</tr></thead><tbody>{preview.slice(0,30).map(x=><tr key={x.sourceLine}><td style={{padding:6}}>{x.sourceLine}</td><td>{x.description}</td><td>{money(x.amount)}</td><td>{x.dueDate}</td><td>{x.categoryName||"—"}</td><td>{x.supplierName||"—"}</td></tr>)}</tbody></table></div><button onClick={importRows} style={{marginTop:12,background:"#4a9410",color:"#fff",border:0,borderRadius:8,padding:"9px 18px",fontWeight:700}}>Confirmar importação de {preview.length} linhas</button></>}</div>}
 {tab==="ia"&&<div style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:12,padding:16}}><h3 style={{fontSize:14,color:"#334532"}}>Leitura estruturada com validação humana</h3><p style={{fontSize:11,color:"#6b7280"}}>Cole o texto extraído de boleto, nota ou comprovante. PDFs textuais também são aceitos pela API; documentos escaneados exigem OCR externo e não terão dados inventados.</p><textarea style={{...estiloInput,minHeight:180}} value={docText} onChange={e=>setDocText(e.target.value)}/><button onClick={extract} disabled={docText.length<20} style={{marginTop:9,background:"#7c3aed",color:"#fff",border:0,borderRadius:8,padding:"9px 18px",fontWeight:700}}>Analisar com IA</button>{ai&&<div style={{marginTop:12,background:"#f9fafb",borderRadius:9,padding:12}}><strong>{ai.data.documentType}</strong> · confiança {ai.data.confidence}%<pre style={{fontSize:11,whiteSpace:"pre-wrap"}}>{JSON.stringify(ai.data,null,2)}</pre>{ai.requiresReview&&<div style={{color:"#991b1b",fontWeight:700,fontSize:11}}>Revisão humana obrigatória antes do lançamento.</div>}</div>}</div>}
 </div>;
}
