"use client";
import { useEffect, useState } from "react";
import { estiloInput, estiloLabel } from "@/lib/estilos";

const empty:any={roleName:"",version:1,pgrReference:"",pcmsoReference:"",activities:"",risks:"",exams:"",trainings:"",epis:"",mandatoryDocuments:"",validFrom:new Date().toISOString().slice(0,10),active:true,notes:""};
const parse=(text:string)=>text.split("\n").map(x=>x.trim()).filter(Boolean).map(line=>{const [name,code,days,notes]=line.split("|").map(x=>x?.trim());return{name,code:code||undefined,validityDays:days?Number(days):undefined,notes:notes||undefined,mandatory:true};});
const lines=(arr:any[])=>Array.isArray(arr)?arr.map(x=>[x.name,x.code,x.validityDays,x.notes].filter(v=>v!==undefined&&v!=="").join(" | ")).join("\n"):"";
export default function MatrizSstPage(){
 const [data,setData]=useState<any[]>([]);const [f,setF]=useState<any>(empty);const [msg,setMsg]=useState("");
 const load=()=>fetch("/api/rh/matriz-sst").then(r=>r.json()).then(j=>setData(j.data||[]));useEffect(()=>{load();},[]);
 const set=(k:string,v:any)=>setF((p:any)=>({...p,[k]:v}));
 const edit=(x:any)=>setF({id:x.id,roleName:x.role_name,version:x.version,pgrReference:x.pgr_reference||"",pcmsoReference:x.pcmso_reference||"",activities:lines(x.activities),risks:lines(x.risks),exams:lines(x.exams),trainings:lines(x.trainings),epis:lines(x.epis),mandatoryDocuments:lines(x.mandatory_documents),validFrom:x.valid_from?new Date(x.valid_from).toISOString().slice(0,10):"",validUntil:x.valid_until?new Date(x.valid_until).toISOString().slice(0,10):"",active:x.active,approvedBy:x.approved_by||"",notes:x.notes||""});
 const save=async()=>{setMsg("");const body={...f,activities:parse(f.activities),risks:parse(f.risks),exams:parse(f.exams),trainings:parse(f.trainings),epis:parse(f.epis),mandatoryDocuments:parse(f.mandatoryDocuments),version:Number(f.version)};const r=await fetch("/api/rh/matriz-sst",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok){setMsg(j.error||"Erro");return;}setMsg("✅ Matriz salva e disponível para mobilizações e OS.");setF(empty);load();};
 const Area=({k,label,hint}:{k:string,label:string,hint:string})=><div><label style={estiloLabel}>{label}</label><textarea style={{...estiloInput,minHeight:100}} value={f[k]||""} onChange={e=>set(k,e.target.value)} placeholder={hint}/></div>;
 return <div><h1 style={{margin:"0 0 4px",color:"#334532",fontSize:22}}>🛡️ Matriz PGR · PCMSO · Função · NR · EPI</h1><p style={{fontSize:12,color:"#6b7280",margin:"0 0 14px"}}>Cadastre somente dados validados nos documentos oficiais. Formato por linha: <b>Nome | Código | validade em dias | observação</b>.</p>
 <div style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:12,padding:16,marginBottom:14}}><div style={{display:"grid",gridTemplateColumns:"2fr 100px 1fr 1fr",gap:9}}><div><label style={estiloLabel}>Função</label><input style={estiloInput} value={f.roleName} onChange={e=>set("roleName",e.target.value)}/></div><div><label style={estiloLabel}>Versão</label><input type="number" style={estiloInput} value={f.version} onChange={e=>set("version",e.target.value)}/></div><div><label style={estiloLabel}>Referência PGR</label><input style={estiloInput} value={f.pgrReference} onChange={e=>set("pgrReference",e.target.value)}/></div><div><label style={estiloLabel}>Referência PCMSO</label><input style={estiloInput} value={f.pcmsoReference} onChange={e=>set("pcmsoReference",e.target.value)}/></div></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:10,marginTop:12}}><Area k="activities" label="Atividades" hint="Operação de roçadeira | AT-01"/><Area k="risks" label="Riscos" hint="Ruído contínuo | FIS-01"/><Area k="exams" label="Exames ocupacionais" hint="Audiometria | AUD | 365"/><Area k="trainings" label="Treinamentos / NRs" hint="NR-12 | NR12 | 730"/><Area k="epis" label="EPIs" hint="Protetor auricular | CA 12345 | 180"/><Area k="mandatoryDocuments" label="Documentos obrigatórios" hint="ASO | ASO | 365"/></div>
 <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 2fr",gap:9,marginTop:10}}><div><label style={estiloLabel}>Vigência inicial</label><input type="date" style={estiloInput} value={f.validFrom} onChange={e=>set("validFrom",e.target.value)}/></div><div><label style={estiloLabel}>Vigência final</label><input type="date" style={estiloInput} value={f.validUntil||""} onChange={e=>set("validUntil",e.target.value)}/></div><div><label style={estiloLabel}>Observações</label><input style={estiloInput} value={f.notes||""} onChange={e=>set("notes",e.target.value)}/></div></div><label style={{display:"block",fontSize:11,marginTop:9}}><input type="checkbox" checked={!!f.active} onChange={e=>set("active",e.target.checked)}/> Versão ativa e aprovada</label>{msg&&<div style={{marginTop:9,fontSize:12,color:msg.startsWith("✅")?"#15803d":"#991b1b"}}>{msg}</div>}<button onClick={save} disabled={!f.roleName} style={{marginTop:11,background:"#4a9410",color:"#fff",border:0,borderRadius:8,padding:"9px 22px",fontWeight:700}}>Salvar matriz</button></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:9}}>{data.map(x=><div key={x.id} style={{background:"#fff",border:`1px solid ${x.active?"#86efac":"#e5e7eb"}`,borderRadius:11,padding:13}}><div style={{display:"flex",justifyContent:"space-between"}}><strong style={{color:"#334532"}}>{x.role_name}</strong><span style={{fontSize:10,fontWeight:700,color:x.active?"#15803d":"#6b7280"}}>v{x.version} · {x.active?"ATIVA":"HISTÓRICA"}</span></div><div style={{fontSize:10,color:"#6b7280",margin:"5px 0"}}>PGR: {x.pgr_reference||"não informado"} · PCMSO: {x.pcmso_reference||"não informado"}</div><div style={{fontSize:11}}>Exames: {x.exams?.length||0} · NRs: {x.trainings?.length||0} · EPIs: {x.epis?.length||0} · Docs: {x.mandatory_documents?.length||0}</div><button onClick={()=>edit(x)} style={{marginTop:8,border:0,borderRadius:6,padding:"5px 9px",background:"#dbeafe",color:"#1d4ed8"}}>Editar</button></div>)}</div></div>;
}
